export default {
  PRIMARY_COLOR: '#4684FE',
  LANDING_LOGO_SIZE: 99,
  APP_NAME: 'CAPTAIN',
  LANDING_LOGO_LABEL_SIZE: 24,
  APP_BACKGROUND_COLOR: '#F6F6F6',
  APP_BACKGROUND_ALTERNATE_COLOR: '',
  APP_STORAGE_KEY: 'ASYNC_STORAGE_COMMENTS_KEY'
} 